#!/bin/sh

# Exit immediately if a command exits with a non-zero status.
set -e

echo_command() {
    local cmd="$1"
    local first_arg="$2"
    shift 2

    # Print the command and arguments with formatting
    printf "\n> \033[1;36m$cmd\033[0m $first_arg \033[0;90m$*\033[0m"

    # Execute the original command with all arguments
    "$cmd" "$first_arg" "$@"
}

format_staged_files() {
    FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E "\.(css|html|mjs|js|json|md|ts|svelte|yaml)$" | sed 's| |\\ |g')
    if [ -z "$FILES" ]; then
        printf "\033[0;33m\nNo files to format.\033[0m"
        return
    fi
    echo_command pnpm prettier $FILES --cache --write --config ./config/prettier.config.mjs --ignore-path ./config/.prettierignore
    echo_command git add $FILES
}

lint_staged_files() {
    FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E "\.(mjs|js|svelte|ts)$" | sed 's| |\\ |g')
    if [ -z "$FILES" ]; then
        printf "\033[0;33m\nNo files to lint.\033[0m"
        return
    fi
    echo_command pnpm eslint --color --cache --fix --config ./config/eslint.config.js --cache-location ./config/.eslintcache $FILES
    echo_command git add $FILES
}

format_staged_files
lint_staged_files
pnpm run pre-commit
