packages:
    - config
    - packages/*
    - sites/*
catalog:
    '@changesets/cli': ^2.29.4
    '@content-thing/memdb': ^0.0.10
    '@mdi/js': ^7.4.47
    '@svelte-thing/component-utils': ^0.0.10
    '@svelte-thing/dom-event': ^0.0.5
    '@sveltejs/adapter-auto': ^6.0.1
    '@sveltejs/kit': ^2.21.1
    '@sveltejs/package': ^2.3.11
    '@sveltejs/vite-plugin-svelte': ^5.0.3
    '@vitest/browser': ^3.1.4
    eslint: ^9.27.0
    eslint-config-prettier: ^10.1.5
    eslint-plugin-svelte: ^3.9.0
    esm-env: ^1.2.2
    globals: ^16.2.0
    jsdom: ^26.1.0
    playwright: ^1.52.0
    prettier: ^3.5.3
    prettier-plugin-svelte: ^3.4.0
    publint: ^0.3.12
    svelte: ^5.33.2
    svelte-check: ^4.2.1
    typescript: ^5.8.3
    typescript-eslint: ^8.32.1
    uid: ^2.0.2
    vite: ^6.0.11
    vitest: ^3.1.4
    vitest-browser-svelte: ^0.1.0
    wireit: ^0.14.12
